"""Add submission_note and revision_note to applications

Revision ID: 001
Revises: 
Create Date: 2026-02-19 22:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('submission_note', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('revision_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'revision_note')
    op.drop_column('applications', 'submission_note')
    # ### end Alembic commands ###
